### PR TITLE
Feature: Useable Events / Schedule Page

### LINKED ISSUE #96: Schedule Page: Set up Sanity Queries
Now that a basic clipboard structure has been created, we should create Sanity queries and load query results onto the page. One way to do this is to have one query get all the events and then parse them into their respective days.

### PR DESCRIPTION
**Pull request by alexanderl19**
closes #96

### CODE REVIEW

**Comment by alexanderl19** [comment]
Okay, as expected, dates are messed up because they're being grouped by the UTC day. I'm going to introduce [Day.js](https://day.js.org/) as a dependency to address this.

**Comment by tyleryy** [comment]
image

On mobile view, the text is extends to an odd amount of lines (2-4). Will approve for now due to deadlines. Can either resolve now in this PR or in another PR possibly, your call.

**Comment by alexanderl19** [comment]
We should probably shift the location and time to a separate line. I'll probably open another PR after this to display org name, host names, and fix that.

**Comment by alexanderl19** [comment]
Sorry, forgot to set the order correctly. One more push and this PR should be good.

**Comment by alexanderl19** [comment]
A few notes for tomorrow (today):

- The SSR rendered version of the page still has incorrect dates
- Separate title and location / time on mobile
- Org
- Hosts
- Virtual Link

**Review by tyleryy — APPROVED** [review]
Lgtm

**Pull request merged**
