### PR TITLE
feature: clipboard paper animation

### PR DESCRIPTION
**Pull request by tyleryy**
### Overview

Clipboard paper animates upward to simulate the paper schedule being "snapped" into the clipboard's clip.

### Details

Animate variant just animates the y coords from below to its original position. Decoupled the clipboard brown border and white background into two divs to create the animation.

### CODE REVIEW

**Review by samderanova — APPROVED** [review]
Looks good, thanks for working on this.

**Comment by samderanova** [comment]
Please resolve the conflicts first.

**Review by samderanova — CHANGES_REQUESTED** [review]
This should be a very quick fix, but for accessibility, please disable the clipboard animation for users that prefer reduced motion. See https://www.framer.com/motion/use-reduced-motion/ on how to do this.

**Comment by tyleryy** [comment]
Screen Shot 2023-11-03 at 12 28 58 AM

The prefersReducedMotion is actually a bit difficult to implement due to SSR. I think it because Framer Motion is compatible with SSR so the CSS from Framer is already loaded into the component when it is bundled and then served to client. But the useReducedMotion hook is client side after hydration, so it is able to cancel the "animate" Framer Motion CSS but not the "initial" Framer Motion CSS, which I believe is SSRed. I could be completely wrong about this, but I think this is what is happening because the "initial" will show but not the "animate" if I conditionally render the variant. I don't think it is worth pursuing this imo.

**Comment by samderanova** [comment]
Ok no worries. Let's merge then.

**Review by samderanova — APPROVED** [review]

**Pull request merged**
