### PR TITLE
Temporarily disable navbar and other pages

### PR DESCRIPTION
**Pull request by samderanova**

### CODE REVIEW

**Comment by tyleryy** [comment]
The schedule route is still up.

**Comment by samderanova** [comment]
I thought we agreed to hiding the resources page, but not the schedule?

**Comment by samderanova** [comment]
> The schedule route is still up.

Removed!

**Comment by tyleryy** [comment]
Nice, thanks for working quickly on this! lgtm!

**Review by tyleryy — APPROVED** [review]

**Pull request merged**
